[[edge_functions]]
  function = "hello-edge"
  path = "/edge"

[[edge_functions]]
  function = "date-now"
  path = "/date-now"

[[edge_functions]]
  function = "use-context"
  path = "/context"

[[edge_functions]]
  function = "hello-edge"
  path = "/context"
